# Generated by Django 2.2.6 on 2019-11-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=200)),
                ('card_description', models.CharField(max_length=200)),
                ('card_level', models.IntegerField()),
                ('card_ct_choice', models.CharField(max_length=200)),
                ('card_wr_choice', models.CharField(max_length=200)),
                ('card_image_path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'card',
            },
        ),
    ]
