# Generated by Django 2.2.6 on 2019-11-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191103_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cash', models.FloatField()),
                ('current_approval', models.IntegerField()),
                ('current_client_satisfaction', models.IntegerField()),
                ('current_employees_satisfaction', models.IntegerField()),
                ('current_overrall_satisfaction', models.IntegerField()),
                ('current_level', models.IntegerField()),
            ],
            options={
                'db_table': 'gamestate',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_profile_picture_path', models.CharField(blank=True, max_length=200)),
                ('user_current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GameState')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_cash_ct_effect', models.IntegerField()),
                ('card_cash_wr_effect', models.IntegerField()),
                ('card_approval_ct_effect', models.IntegerField()),
                ('card_approval_wr_effect', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Card')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
